### ISSUE TITLE
Use btrfs as root filesystem

### ISSUE THREAD

**Issue by derchr** [radxa-repo/rbuild#56]
Hello,
is it possible to create a system image that uses btrfs as the root partition file system?
I've seen that recently, the default kernel configuration gained support for btrfs.

What changes to the configuration would need to be done and has u-boot also to be configured accordingly?

Thanks!

**Comment by RadxaYuntian** [comment]
I don't think U-Boot supports btrfs natively, so to use it (or any unsupported file system for that matter), you will need to chain bootloader like on x86 PCs. That probably means to use systemd-boot as an UEFI payload. The last time I tried grub2 it didn't boot, and I'm not sure if it can support overlays (which sd-boot supports with [`devicetree-overlay` keyword](https://uapi-group.org/specifications/specs/boot_loader_specification/)).

Since some of our Rockchip devices are using Rockchip U-Boot (which can trace its origin to 2017 upstream release), we are not confident to do UEFI with their bootloader. We also don't want to further fragment the system configurations, so for now we are settled on the lowest common denominator that is ext4.
